-- Seed data for PriceRoute MVP
-- This script is designed to be idempotent.

-- Use temporary tables to define products and offers to make linking them easier.

-- 1. Define Products in a temporary table
CREATE TEMP TABLE IF NOT EXISTS temp_products (
    id UUID,
    title TEXT,
    brand TEXT,
    description TEXT,
    image_urls TEXT[]
);

-- Clear temp table before use
TRUNCATE temp_products;

INSERT INTO temp_products (id, title, brand, description, image_urls) VALUES
('a1b2c3d4-e5f6-7890-1234-567890abcdef', 'High-Performance Wireless Headphones', 'SoundWave', 'Experience immersive sound with these noise-cancelling wireless headphones. Features 30-hour battery life and a comfortable, lightweight design.', ARRAY['https://i.imgur.com/3j3XqXj.jpeg', 'https://i.imgur.com/6Xq7aP2.jpeg']),
('b2c3d4e5-f6a7-8901-2345-67890abcdef0', 'Smart Fitness Tracker Watch', 'FitLife', 'Track your workouts, heart rate, and sleep patterns with this sleek and waterproof fitness tracker. Syncs with your smartphone for notifications.', ARRAY['https://i.imgur.com/sC5Iay3.jpeg', 'https://i.imgur.com/sC5Iay3.jpeg']),
('c3d4e5f6-a7b8-9012-3456-7890abcdef01', '4K Action Camera', 'GoPro', 'Capture your adventures in stunning 4K. Waterproof, durable, and packed with features.', ARRAY['https://i.imgur.com/sC5Iay3.jpeg']),
('d4e5f6a7-b8c9-0123-4567-890abcdef012', 'Ergonomic Office Chair', 'ComfortZone', 'Stay comfortable and productive with this ergonomic chair, featuring lumbar support and adjustable armrests.', ARRAY['https://i.imgur.com/sC5Iay3.jpeg']);


-- Insert products into the main table, avoiding duplicates
INSERT INTO public.products (canonical_id, title, brand, description, image_urls)
SELECT id, title, brand, description, image_urls FROM temp_products
ON CONFLICT (canonical_id) DO NOTHING;


-- 2. Define Offers in a temporary table
CREATE TEMP TABLE IF NOT EXISTS temp_offers (
    product_title TEXT,
    seller_name TEXT,
    marketplace TEXT,
    price NUMERIC(10,2),
    currency TEXT,
    shipping_est NUMERIC(10,2),
    eta_days INT,
    rating NUMERIC(3,2),
    reviews_count INT,
    affiliate_link TEXT
);

TRUNCATE temp_offers;

INSERT INTO temp_offers (product_title, seller_name, marketplace, price, currency, shipping_est, eta_days, rating, reviews_count, affiliate_link) VALUES
-- Offers for Headphones
('High-Performance Wireless Headphones', 'ElectroDeals', 'Amazon', 199.99, 'USD', 5.99, 3, 4.8, 1250, 'http://amazon.com/aff/link1'),
('High-Performance Wireless Headphones', 'GadgetGalaxy', 'AliExpress', 175.50, 'USD', 10.00, 15, 4.5, 890, 'http://aliexpress.com/aff/link2'),
('High-Performance Wireless Headphones', 'TechBargains', 'Temu', 165.00, 'USD', 0.00, 20, 4.3, 450, 'http://temu.com/aff/link3'),
('High-Performance Wireless Headphones', 'Official SoundWave Store', 'Shopify', 219.99, 'USD', 0.00, 2, 4.9, 3200, 'http://soundwave.com/aff/link4'),
-- Offers for Watch
('Smart Fitness Tracker Watch', 'BestBuy', 'Amazon', 89.99, 'USD', 4.99, 2, 4.7, 4300, 'http://amazon.com/aff/link5'),
('Smart Fitness Tracker Watch', 'GlobalElectronics', 'AliExpress', 65.00, 'USD', 8.50, 18, 4.4, 2100, 'http://aliexpress.com/aff/link6'),
('Smart Fitness Tracker Watch', 'DailyDeals', 'Temu', 59.99, 'USD', 0.00, 25, 4.1, 980, 'http://temu.com/aff/link7'),
('Smart Fitness Tracker Watch', 'FitLife Direct', 'Shopify', 99.99, 'USD', 2.99, 3, 4.8, 5600, 'http://fitlife.com/aff/link8'),
-- Offers for Action Camera
('4K Action Camera', 'AdventureGear', 'Amazon', 349.00, 'USD', 0.00, 2, 4.9, 7800, 'http://amazon.com/aff/link9'),
('4K Action Camera', 'PhotoWorld', 'AliExpress', 299.50, 'USD', 12.00, 14, 4.6, 3400, 'http://aliexpress.com/aff/link10'),
-- Offers for Office Chair
('Ergonomic Office Chair', 'OfficeMax', 'Amazon', 250.00, 'USD', 50.00, 5, 4.5, 1500, 'http://amazon.com/aff/link11'),
('Ergonomic Office Chair', 'HomeComforts', 'Shopify', 275.00, 'USD', 45.00, 7, 4.7, 950, 'http://shopify.com/aff/link12');

-- 3. Insert offers into the main table, linking them to products by title
-- Note: This assumes product titles are unique.
INSERT INTO public.seller_offers (product_id, seller_name, marketplace, price, currency, shipping_est, eta_days, rating, reviews_count, affiliate_link)
SELECT p.canonical_id, t.seller_name, t.marketplace, t.price, t.currency, t.shipping_est, t.eta_days, t.rating, t.reviews_count, t.affiliate_link
FROM temp_offers t
JOIN public.products p ON p.title = t.product_title;


-- 4. Clean up temporary tables
DROP TABLE temp_products;
DROP TABLE temp_offers;

-- Note: This seed script does not create price snapshots or watchlists,
-- as those would typically be generated by application usage.
-- It also doesn't create users, which should be done via Supabase Auth.
